language: python
cache: pip
matrix:
  include:
    - name: "Python <=3.6"
      sudo: false
      python:
        - "2.7"
        - "3.3"
        - "3.4"
        - "3.5"
        - "3.6"
        - "3.7"
    - name: "Python >3.6"
      sudo: required
      python: 3.7
      dist: xenial
install: "pip install -r requirements.txt"
script:
  - pytest
  - pip install -e .
  - travis_wait 60 python tests/test_compatibility.py tests/password_expected_value.json
notifications:
  email:
    on_success: never
